apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fibonacci-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibonacci-api
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50